---
galaxy_info:
  author: Praktikan 1
  description: Role untuk instalasi Docker Engine dan setup firewall
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
dependencies: []
