all:
  children:
    backend:
      hosts:
        node1:
          ansible_host: 10.166.149.18   # IP Multipass node 1
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
      vars:
        db_name: vibe_db
        db_username: vibe_user
        db_password: supersecretpassword
        backend_port: 3000
        jwt_secret: secretjwtkey
    frontend:
      hosts:
        node2:
          ansible_host: 10.166.149.13    # IP Multipass node 2
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
      vars:
        frontend_port: 8080
        backend_url: "http://localhost:3000"
