---
# ============================================================
# Playbook Utama: Site Playbook
# Deskripsi: Memberikan semua node dalam inventory role Docker
# ============================================================

- name: Install Docker Engine pada semua node
  hosts: all
  become: yes
  roles:
    - docker

- name: Deploy Backend ke group backend
  hosts: backend
  become: yes
  roles:
    - backend

- name: Deploy Frontend ke group frontend
  hosts: frontend
  become: yes
  roles:
    - frontend
